// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLYe5l0ThiHc5MlVhwFZpUR1jm5rKfG00',
    appId: '1:107640323589:web:f165a081d6d69d9af3666c',
    messagingSenderId: '107640323589',
    projectId: 'flutter-uceva2',
    authDomain: 'flutter-uceva2.firebaseapp.com',
    storageBucket: 'flutter-uceva2.firebasestorage.app',
    measurementId: 'G-3WH6WNM67S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcMyK_8UD0BOVd7EfgG_8nwWJnpFBN5SM',
    appId: '1:107640323589:android:8d06c0150e56a230f3666c',
    messagingSenderId: '107640323589',
    projectId: 'flutter-uceva2',
    storageBucket: 'flutter-uceva2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwuAvIf1e7Hyq6yqv-RW_ubiOxU0u9XkE',
    appId: '1:107640323589:ios:a77b6537171554b1f3666c',
    messagingSenderId: '107640323589',
    projectId: 'flutter-uceva2',
    storageBucket: 'flutter-uceva2.firebasestorage.app',
    iosBundleId: 'com.example.flutterUceva2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwuAvIf1e7Hyq6yqv-RW_ubiOxU0u9XkE',
    appId: '1:107640323589:ios:a77b6537171554b1f3666c',
    messagingSenderId: '107640323589',
    projectId: 'flutter-uceva2',
    storageBucket: 'flutter-uceva2.firebasestorage.app',
    iosBundleId: 'com.example.flutterUceva2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLYe5l0ThiHc5MlVhwFZpUR1jm5rKfG00',
    appId: '1:107640323589:web:78bedaa62147e74af3666c',
    messagingSenderId: '107640323589',
    projectId: 'flutter-uceva2',
    authDomain: 'flutter-uceva2.firebaseapp.com',
    storageBucket: 'flutter-uceva2.firebasestorage.app',
    measurementId: 'G-JY2WKPTMB9',
  );
}
